# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accounts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("background: #f7f6fb")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(-60, -190, 391, 391))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("resources/small_logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(375, 80, 400, 70))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAutoFillBackground(False)
        self.titleLabel.setStyleSheet("color: #003780; background:None; text-align: center;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.depositWidget = QtWidgets.QWidget(self.centralwidget)
        self.depositWidget.setGeometry(QtCore.QRect(350, 250, 200, 200))
        self.depositWidget.setStyleSheet("QWidget {border: 3px solid; border-color: #003780;border-radius:100px; background: white}\n"
"\n"
"QWidget:hover{background-color: rgb(235, 233, 241);\n"
"}")
        self.depositWidget.setObjectName("depositWidget")
        self.depositLabel = QtWidgets.QLabel(self.depositWidget)
        self.depositLabel.setGeometry(QtCore.QRect(50, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.depositLabel.setFont(font)
        self.depositLabel.setStyleSheet("border: None; color: #003780; text-align: center; background:None")
        self.depositLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.depositLabel.setObjectName("depositLabel")
        self.depositAmountLabel = QtWidgets.QLabel(self.depositWidget)
        self.depositAmountLabel.setGeometry(QtCore.QRect(0, 80, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.depositAmountLabel.setFont(font)
        self.depositAmountLabel.setStyleSheet("border:None;background:None")
        self.depositAmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.depositAmountLabel.setObjectName("depositAmountLabel")
        self.CNYWidget = QtWidgets.QWidget(self.centralwidget)
        self.CNYWidget.setGeometry(QtCore.QRect(850, 250, 200, 200))
        self.CNYWidget.setStyleSheet("QWidget {border: 3px solid; border-color: #003780;border-radius:100px; background: white}\n"
"\n"
"QWidget:hover{background-color: rgb(235, 233, 241);\n"
"}")
        self.CNYWidget.setObjectName("CNYWidget")
        self.cnyLabel = QtWidgets.QLabel(self.CNYWidget)
        self.cnyLabel.setGeometry(QtCore.QRect(50, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cnyLabel.setFont(font)
        self.cnyLabel.setStyleSheet("border: None; color: #003780; text-align: center; background:None")
        self.cnyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cnyLabel.setObjectName("cnyLabel")
        self.cnyAmountLabel = QtWidgets.QLabel(self.CNYWidget)
        self.cnyAmountLabel.setGeometry(QtCore.QRect(0, 80, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.cnyAmountLabel.setFont(font)
        self.cnyAmountLabel.setStyleSheet("border:None;background:None")
        self.cnyAmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cnyAmountLabel.setObjectName("cnyAmountLabel")
        self.USDWidget = QtWidgets.QWidget(self.centralwidget)
        self.USDWidget.setGeometry(QtCore.QRect(600, 250, 200, 200))
        self.USDWidget.setStyleSheet("QWidget {border: 3px solid; border-color: #003780;border-radius:100px; background: white}\n"
"\n"
"QWidget:hover{background-color: rgb(235, 233, 241);\n"
"}")
        self.USDWidget.setObjectName("USDWidget")
        self.usdLabel = QtWidgets.QLabel(self.USDWidget)
        self.usdLabel.setGeometry(QtCore.QRect(50, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.usdLabel.setFont(font)
        self.usdLabel.setStyleSheet("border: None; color: #003780; text-align: center; background:None")
        self.usdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usdLabel.setObjectName("usdLabel")
        self.usdAmountLabel = QtWidgets.QLabel(self.USDWidget)
        self.usdAmountLabel.setGeometry(QtCore.QRect(0, 80, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.usdAmountLabel.setFont(font)
        self.usdAmountLabel.setStyleSheet("border:None;background:None")
        self.usdAmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usdAmountLabel.setObjectName("usdAmountLabel")
        self.HKDWidge = QtWidgets.QWidget(self.centralwidget)
        self.HKDWidge.setGeometry(QtCore.QRect(100, 250, 200, 200))
        self.HKDWidge.setStyleSheet("QWidget {border: 3px solid; border-color: #003780;border-radius:100px; background: white}\n"
"\n"
"QWidget:hover{background-color: rgb(235, 233, 241);\n"
"}")
        self.HKDWidge.setObjectName("HKDWidge")
        self.hkdLabel = QtWidgets.QLabel(self.HKDWidge)
        self.hkdLabel.setGeometry(QtCore.QRect(50, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.hkdLabel.setFont(font)
        self.hkdLabel.setStyleSheet("border: None; color: #003780; text-align: center; background:None")
        self.hkdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hkdLabel.setObjectName("hkdLabel")
        self.hkdAmountLabel = QtWidgets.QLabel(self.HKDWidge)
        self.hkdAmountLabel.setGeometry(QtCore.QRect(0, 80, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.hkdAmountLabel.setFont(font)
        self.hkdAmountLabel.setStyleSheet("border:None;background:None")
        self.hkdAmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hkdAmountLabel.setObjectName("hkdAmountLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(950, 510, 100, 100))
        self.pushButton.setStyleSheet("QPushButton{background:#004094; background-image : url(resources/back.png); background-repeat: no-repeat; background-position: center; border-radius: 50px;}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(0, 71, 163);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iKYC"))
        self.titleLabel.setText(_translate("MainWindow", "My Accounts"))
        self.depositLabel.setText(_translate("MainWindow", "Deposit"))
        self.depositAmountLabel.setAccessibleName(_translate("MainWindow", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_7\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>0</x>\n"
"     <y>80</y>\n"
"     <width>200</width>\n"
"     <height>40</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"font\">\n"
"    <font>\n"
"     <family>Yu Gothic</family>\n"
"     <pointsize>22</pointsize>\n"
"     <weight>50</weight>\n"
"     <bold>false</bold>\n"
"    </font>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">border:None;background:None</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>$10,000</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
""))
        self.depositAmountLabel.setText(_translate("MainWindow", "$10,000"))
        self.cnyLabel.setText(_translate("MainWindow", "CNY"))
        self.cnyAmountLabel.setAccessibleName(_translate("MainWindow", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_7\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>0</x>\n"
"     <y>80</y>\n"
"     <width>200</width>\n"
"     <height>40</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"font\">\n"
"    <font>\n"
"     <family>Yu Gothic</family>\n"
"     <pointsize>22</pointsize>\n"
"     <weight>50</weight>\n"
"     <bold>false</bold>\n"
"    </font>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">border:None;background:None</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>$10,000</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
""))
        self.cnyAmountLabel.setText(_translate("MainWindow", "￥10,000"))
        self.usdLabel.setText(_translate("MainWindow", "USD"))
        self.usdAmountLabel.setAccessibleName(_translate("MainWindow", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_7\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>0</x>\n"
"     <y>80</y>\n"
"     <width>200</width>\n"
"     <height>40</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"font\">\n"
"    <font>\n"
"     <family>Yu Gothic</family>\n"
"     <pointsize>22</pointsize>\n"
"     <weight>50</weight>\n"
"     <bold>false</bold>\n"
"    </font>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">border:None;background:None</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>$10,000</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
""))
        self.usdAmountLabel.setText(_translate("MainWindow", "$10,000"))
        self.hkdLabel.setText(_translate("MainWindow", "HKD"))
        self.hkdAmountLabel.setText(_translate("MainWindow", "$10,000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
