# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountsDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 769)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: #f7f6fb")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(-60, -190, 391, 391))
        self.logoLabel.setStyleSheet("QScrollBar::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253), stop:1 rgb(139, 229, 253));\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0  rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::handle:horizon {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253), stop:1 rgb(139, 229, 253));\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:horizon {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizon {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0  rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("resources/small_logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(370, 50, 541, 101))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(39)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAutoFillBackground(False)
        self.titleLabel.setStyleSheet("color: #003780; background:None; text-align: center;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 540, 100, 100))
        self.pushButton.setStyleSheet("QPushButton{background:#004094; background-image : url(resources/back.png); background-repeat: no-repeat; background-position: center; border-radius: 50px;}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(0, 71, 163);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(80, 240, 591, 191))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"}\n"
"QScrollBar:vertical {       \n"
"    background:transparent;\n"
"    width:10px;\n"
"    margin:0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253), stop:1 rgb(139, 229, 253));\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0  rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal {       \n"
"    background:transparent;\n"
"    height:10px;\n"
"    margin:0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253), stop:1 rgb(139, 229, 253));\n"
"    min-width: 0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0  rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    width: 0 px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(113)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
        self.tableWidget.verticalHeader().setMinimumSectionSize(21)
        self.HKDWidge = QtWidgets.QWidget(self.centralwidget)
        self.HKDWidge.setGeometry(QtCore.QRect(800, 230, 200, 200))
        self.HKDWidge.setStyleSheet("QWidget {border: 3px solid; border-color: #003780;border-radius:100px; background: white}\n"
"")
        self.HKDWidge.setObjectName("HKDWidge")
        self.hkdLabel = QtWidgets.QLabel(self.HKDWidge)
        self.hkdLabel.setGeometry(QtCore.QRect(50, 30, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.hkdLabel.setFont(font)
        self.hkdLabel.setStyleSheet("border: None; color: #003780; text-align: center; background:None")
        self.hkdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hkdLabel.setObjectName("hkdLabel")
        self.hkdAmountLabel = QtWidgets.QLabel(self.HKDWidge)
        self.hkdAmountLabel.setGeometry(QtCore.QRect(0, 80, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.hkdAmountLabel.setFont(font)
        self.hkdAmountLabel.setStyleSheet("border:None;background:None")
        self.hkdAmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hkdAmountLabel.setObjectName("hkdAmountLabel")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(80, 500, 591, 191))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"}\n"
"QScrollBar:vertical {       \n"
"    background:transparent;\n"
"    width:10px;\n"
"    margin:0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253), stop:1 rgb(139, 229, 253));\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0  rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal {       \n"
"    background:transparent;\n"
"    height:10px;\n"
"    margin:0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253), stop:1 rgb(139, 229, 253));\n"
"    min-width: 0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0  rgb(139, 229, 253), stop: 0.5 rgb(139, 229, 253),  stop:1 rgb(139, 229, 253));\n"
"    width: 0 px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_2.setRowCount(5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 4, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(114)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(38)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 200, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 460, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 730, 113, 32))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: rgb(245, 243, 251);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780\n"
"}\n"
"QPushButton:hover{\n"
"    background: rgb(235, 233, 241);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: rgb(226, 224, 231);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 730, 113, 32))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background: rgb(245, 243, 251);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780\n"
"}\n"
"QPushButton:hover{\n"
"    background: rgb(235, 233, 241);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: rgb(226, 224, 231);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 730, 113, 32))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background: rgb(245, 243, 251);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780\n"
"}\n"
"QPushButton:hover{\n"
"    background: rgb(235, 233, 241);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: rgb(226, 224, 231);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 730, 113, 32))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background: rgb(245, 243, 251);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780\n"
"}\n"
"QPushButton:hover{\n"
"    background: rgb(235, 233, 241);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}\n"
"QPushButton:pressed{\n"
"    background: rgb(226, 224, 231);\n"
"    color: #003780;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #003780;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iKYC"))
        self.titleLabel.setText(_translate("MainWindow", "HKD Account"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Transaction Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Currency"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Payee"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "2021-10-24-16-05-33"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "300"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "HKD"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Luo Ping"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "2021-10-24-16-05-33"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "HKD"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "Dirk"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.hkdLabel.setText(_translate("MainWindow", "Balance"))
        self.hkdAmountLabel.setText(_translate("MainWindow", "$10,000"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Transaction Time"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Currency"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Payer"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "2021-10-24-21-00-04\n"
"\n"
""))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "100"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "HKD"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("MainWindow", "Rick"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "2021-10-24-21-00-04\n"
"\n"
""))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "50"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("MainWindow", "HKD"))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("MainWindow", "Joe"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Remittance"))
        self.label_2.setText(_translate("MainWindow", "Received"))
        self.pushButton_2.setText(_translate("MainWindow", "Current"))
        self.pushButton_3.setText(_translate("MainWindow", "Deposit"))
        self.pushButton_4.setText(_translate("MainWindow", "USD"))
        self.pushButton_5.setText(_translate("MainWindow", "RMB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
