# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 801, 511))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap(
            "../chuu__chloe_53349098_373071103421166_776043650774880822_n.jpg"))
        self.photo.setScaledContents(False)
        self.photo.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.photo.setObjectName("photo")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(300, 520, 93, 28))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(410, 520, 93, 28))
        self.button2.setObjectName("button2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button1.clicked.connect(self.show_1)
        self.button2.clicked.connect(self.show_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button2.setText(_translate("MainWindow", "2"))

    def show_1(self):
        self.photo.setPixmap(QtGui.QPixmap(
            "../chuu__chloe_53349098_373071103421166_776043650774880822_n.jpg"))
        self.show_pop_up()

    def show_2(self):
        self.photo.setPixmap(QtGui.QPixmap(
            "../chuu__chloe_66500462_170724000637321_804003549416515037_n.jpg"))
        self.show_pop_up()

    def show_pop_up(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error!")
        msg.setText("You are bad")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Cancel | QMessageBox.Retry | QMessageBox.Ignore)
        msg.setDefaultButton(QMessageBox.Cancel)
        msg.setInformativeText("What the fuck is this?")
        msg.setDetailedText("巴啦啦能量")
        msg.buttonClicked.connect(self.pop_up_button)
        x = msg.exec_()

    def pop_up_button(self, i):
        print(i.text())


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
